require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StatusRecordsController do

  # This should return the minimal set of attributes required to create a valid
  # StatusRecord. As you add validations to StatusRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "student_list_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StatusRecordsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all status_records as @status_records" do
      status_record = StatusRecord.create! valid_attributes
      get :index, {}, valid_session
      assigns(:status_records).should eq([status_record])
    end
  end

  describe "GET show" do
    it "assigns the requested status_record as @status_record" do
      status_record = StatusRecord.create! valid_attributes
      get :show, {:id => status_record.to_param}, valid_session
      assigns(:status_record).should eq(status_record)
    end
  end

  describe "GET new" do
    it "assigns a new status_record as @status_record" do
      get :new, {}, valid_session
      assigns(:status_record).should be_a_new(StatusRecord)
    end
  end

  describe "GET edit" do
    it "assigns the requested status_record as @status_record" do
      status_record = StatusRecord.create! valid_attributes
      get :edit, {:id => status_record.to_param}, valid_session
      assigns(:status_record).should eq(status_record)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StatusRecord" do
        expect {
          post :create, {:status_record => valid_attributes}, valid_session
        }.to change(StatusRecord, :count).by(1)
      end

      it "assigns a newly created status_record as @status_record" do
        post :create, {:status_record => valid_attributes}, valid_session
        assigns(:status_record).should be_a(StatusRecord)
        assigns(:status_record).should be_persisted
      end

      it "redirects to the created status_record" do
        post :create, {:status_record => valid_attributes}, valid_session
        response.should redirect_to(StatusRecord.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved status_record as @status_record" do
        # Trigger the behavior that occurs when invalid params are submitted
        StatusRecord.any_instance.stub(:save).and_return(false)
        post :create, {:status_record => { "student_list_id" => "invalid value" }}, valid_session
        assigns(:status_record).should be_a_new(StatusRecord)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StatusRecord.any_instance.stub(:save).and_return(false)
        post :create, {:status_record => { "student_list_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested status_record" do
        status_record = StatusRecord.create! valid_attributes
        # Assuming there are no other status_records in the database, this
        # specifies that the StatusRecord created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StatusRecord.any_instance.should_receive(:update_attributes).with({ "student_list_id" => "1" })
        put :update, {:id => status_record.to_param, :status_record => { "student_list_id" => "1" }}, valid_session
      end

      it "assigns the requested status_record as @status_record" do
        status_record = StatusRecord.create! valid_attributes
        put :update, {:id => status_record.to_param, :status_record => valid_attributes}, valid_session
        assigns(:status_record).should eq(status_record)
      end

      it "redirects to the status_record" do
        status_record = StatusRecord.create! valid_attributes
        put :update, {:id => status_record.to_param, :status_record => valid_attributes}, valid_session
        response.should redirect_to(status_record)
      end
    end

    describe "with invalid params" do
      it "assigns the status_record as @status_record" do
        status_record = StatusRecord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StatusRecord.any_instance.stub(:save).and_return(false)
        put :update, {:id => status_record.to_param, :status_record => { "student_list_id" => "invalid value" }}, valid_session
        assigns(:status_record).should eq(status_record)
      end

      it "re-renders the 'edit' template" do
        status_record = StatusRecord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StatusRecord.any_instance.stub(:save).and_return(false)
        put :update, {:id => status_record.to_param, :status_record => { "student_list_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested status_record" do
      status_record = StatusRecord.create! valid_attributes
      expect {
        delete :destroy, {:id => status_record.to_param}, valid_session
      }.to change(StatusRecord, :count).by(-1)
    end

    it "redirects to the status_records list" do
      status_record = StatusRecord.create! valid_attributes
      delete :destroy, {:id => status_record.to_param}, valid_session
      response.should redirect_to(status_records_url)
    end
  end

end
