require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TuitionsController do

  # This should return the minimal set of attributes required to create a valid
  # Tuition. As you add validations to Tuition, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "student_list_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TuitionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tuitions as @tuitions" do
      tuition = Tuition.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tuitions).should eq([tuition])
    end
  end

  describe "GET show" do
    it "assigns the requested tuition as @tuition" do
      tuition = Tuition.create! valid_attributes
      get :show, {:id => tuition.to_param}, valid_session
      assigns(:tuition).should eq(tuition)
    end
  end

  describe "GET new" do
    it "assigns a new tuition as @tuition" do
      get :new, {}, valid_session
      assigns(:tuition).should be_a_new(Tuition)
    end
  end

  describe "GET edit" do
    it "assigns the requested tuition as @tuition" do
      tuition = Tuition.create! valid_attributes
      get :edit, {:id => tuition.to_param}, valid_session
      assigns(:tuition).should eq(tuition)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tuition" do
        expect {
          post :create, {:tuition => valid_attributes}, valid_session
        }.to change(Tuition, :count).by(1)
      end

      it "assigns a newly created tuition as @tuition" do
        post :create, {:tuition => valid_attributes}, valid_session
        assigns(:tuition).should be_a(Tuition)
        assigns(:tuition).should be_persisted
      end

      it "redirects to the created tuition" do
        post :create, {:tuition => valid_attributes}, valid_session
        response.should redirect_to(Tuition.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tuition as @tuition" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tuition.any_instance.stub(:save).and_return(false)
        post :create, {:tuition => { "student_list_id" => "invalid value" }}, valid_session
        assigns(:tuition).should be_a_new(Tuition)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tuition.any_instance.stub(:save).and_return(false)
        post :create, {:tuition => { "student_list_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tuition" do
        tuition = Tuition.create! valid_attributes
        # Assuming there are no other tuitions in the database, this
        # specifies that the Tuition created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tuition.any_instance.should_receive(:update_attributes).with({ "student_list_id" => "1" })
        put :update, {:id => tuition.to_param, :tuition => { "student_list_id" => "1" }}, valid_session
      end

      it "assigns the requested tuition as @tuition" do
        tuition = Tuition.create! valid_attributes
        put :update, {:id => tuition.to_param, :tuition => valid_attributes}, valid_session
        assigns(:tuition).should eq(tuition)
      end

      it "redirects to the tuition" do
        tuition = Tuition.create! valid_attributes
        put :update, {:id => tuition.to_param, :tuition => valid_attributes}, valid_session
        response.should redirect_to(tuition)
      end
    end

    describe "with invalid params" do
      it "assigns the tuition as @tuition" do
        tuition = Tuition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tuition.any_instance.stub(:save).and_return(false)
        put :update, {:id => tuition.to_param, :tuition => { "student_list_id" => "invalid value" }}, valid_session
        assigns(:tuition).should eq(tuition)
      end

      it "re-renders the 'edit' template" do
        tuition = Tuition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tuition.any_instance.stub(:save).and_return(false)
        put :update, {:id => tuition.to_param, :tuition => { "student_list_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tuition" do
      tuition = Tuition.create! valid_attributes
      expect {
        delete :destroy, {:id => tuition.to_param}, valid_session
      }.to change(Tuition, :count).by(-1)
    end

    it "redirects to the tuitions list" do
      tuition = Tuition.create! valid_attributes
      delete :destroy, {:id => tuition.to_param}, valid_session
      response.should redirect_to(tuitions_url)
    end
  end

end
